mkdir results  mini_out small_out medium_out large_out extra_out

mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./mini_out/mini1_1.txt --stderr ./mini_out/mini1_1.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./mini_out/mini1_2.txt --stderr ./mini_out/mini1_2.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./mini_out/mini1_3.txt --stderr ./mini_out/mini1_3.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./mini_out/mini2_1.txt --stderr ./mini_out/mini2_1.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./mini_out/mini2_2.txt --stderr ./mini_out/mini2_2.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./mini_out/mini2_3.txt --stderr ./mini_out/mini2_3.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./mini_out/mini3_1.txt --stderr ./mini_out/mini3_1.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./mini_out/mini3_2.txt --stderr ./mini_out/mini3_2.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./mini_out/mini3_3.txt --stderr ./mini_out/mini3_3.err ./mini.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./medium_out/medium1_1.txt --stderr ./medium_out/medium1_1.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./medium_out/medium1_2.txt --stderr ./medium_out/medium1_2.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./medium_out/medium1_3.txt --stderr ./medium_out/medium1_3.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./medium_out/medium2_1.txt --stderr ./medium_out/medium2_1.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./medium_out/medium2_2.txt --stderr ./medium_out/medium2_2.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./medium_out/medium2_3.txt --stderr ./medium_out/medium2_3.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./medium_out/medium3_1.txt --stderr ./medium_out/medium3_1.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./medium_out/medium3_2.txt --stderr ./medium_out/medium3_2.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./medium_out/medium3_3.txt --stderr ./medium_out/medium3_3.err ./medium.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./small_out/small1_1.txt --stderr ./small_out/small1_1.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./small_out/small1_2.txt --stderr ./small_out/small1_2.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./small_out/small1_3.txt --stderr ./small_out/small1_3.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./small_out/small2_1.txt --stderr ./small_out/small2_1.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./small_out/small2_2.txt --stderr ./small_out/small2_2.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./small_out/small2_3.txt --stderr ./small_out/small2_3.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./small_out/small3_1.txt --stderr ./small_out/small3_1.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./small_out/small3_2.txt --stderr ./small_out/small3_2.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./small_out/small3_3.txt --stderr ./small_out/small3_3.err ./small.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./large_out/large1_1.txt --stderr ./large_out/large1_1.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./large_out/large1_2.txt --stderr ./large_out/large1_2.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./large_out/large1_3.txt --stderr ./large_out/large1_3.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./large_out/large2_1.txt --stderr ./large_out/large2_1.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./large_out/large2_2.txt --stderr ./large_out/large2_2.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./large_out/large2_3.txt --stderr ./large_out/large2_3.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./large_out/large3_1.txt --stderr ./large_out/large3_1.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./large_out/large3_2.txt --stderr ./large_out/large3_2.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./large_out/large3_3.txt --stderr ./large_out/large3_3.err ./large.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./extra_out/extra1_1.txt --stderr ./extra_out/extra1_1.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./extra_out/extra1_2.txt --stderr ./extra_out/extra1_2.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=1" --stdout ./extra_out/extra1_3.txt --stderr ./extra_out/extra1_3.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./extra_out/extra2_1.txt --stderr ./extra_out/extra2_1.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./extra_out/extra2_2.txt --stderr ./extra_out/extra2_2.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=2" --stdout ./extra_out/extra2_3.txt --stderr ./extra_out/extra2_3.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./extra_out/extra3_1.txt --stderr ./extra_out/extra3_1.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./extra_out/extra3_2.txt --stderr ./extra_out/extra3_2.err ./extra.o
mpisubmit.bg --nproc 1 -e="OMP_NUM_THREADS=3" --stdout ./extra_out/extra3_3.txt --stderr ./extra_out/extra3_3.err ./extra.o
